language:
  - python
  - r

addons:
  apt:
    packages:
      - bazel
      - r-recommended
    sources:
      -
        key_url: "https://bazel.build/bazel-release.pub.gpg"
        sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
      -
        sourceline: "ppa:marutter/rrutter"
script:
  - "bazel build ..."
  - "bazel test //tests:main_test"
sudo: false

after_failure:
  - cat /home/travis/.cache/bazel/_bazel_travis/b780598bdbf255f7df0b39f918df3247/execroot/__main__/bazel-out/k8-fastbuild/testlogs/tests/main_test/test.log

