library(car)
library(pscl)
library(sqldf)
dat <- read.csv("../data/training_data_21_pol.csv", sep = ",", stringsAsFactor = FALSE)

summary(dat)
table(dat$Hedges)
boxplot(log(1+dat$HASNEGATIVE))
hist(log(1+dat$HASNEGATIVE))
summary(dat$Hedges)
table(log(1+dat$HASNEGATIVE) > 3)


m_pol <- glm((label == 1) ~
               log(1 + HASHEDGE)
             + (Please > 0)
             + (Please_start > 0)
             + (Indirect_.btw. > 0)
             + Hedges
             + (Factuality > 0)
             + (Deference > 0)
             + (Gratitude > 0)
             + (Apologizing > 0)
             + log(1 + X1st_person_pl.)
             + log(1 + X1st_person)
             + log(1 + X1st_person_start)
             + log(1 + X2nd_person)
             + (X2nd_person_start > 0)
             + (Indirect_.greeting. > 0)
             + (Direct_question > 0)
             + log(1 + Direct_start)
             + log(1 + HASPOSITIVE)
             + log(1 + HASNEGATIVE)
             + (SUBJUNCTIVE > 0)
             + (INDICATIVE > 0)
             , data = dat
             , family = "binomial")
summary(m_pol)
vif(m_pol)
pR2(m_pol)
